---
- hosts: localhost
  tags: vagrant
  tasks:
    - name: vagrant spinup
      include_role:
        name: vagrant
      vars:
        vagrant_box_image: "ubuntu/focal64"

- hosts: all
  tags: ping
    - name: pinging server "{{ inventory_hostname }}"
      ping:

