---
- name: ping servers
  hosts: all
  tags: 
    - ping
    - pingpong
  tasks:
    - name: pinging servers in inventory
      ping:

    # - name: printing server ip address
    #   debug:
    #     msg: "Hi from debug module {{ inventory_hostname  }}"

- name: install packages
  hosts: all
  tags: install
  tasks:
    - name: install nginx on ubuntu servers
      apt:
        update_cache: true
        name: nginx
        state: present
      become: true
      when: os_name == 'ubuntu'

    - name: install nginx on rocky servers
      dnf:
        update_cache: true
        name: nginx
        state: present
      become: true
      when: os_name == 'rocky'

    - name: install python3 on rocky servers
      dnf:
        update_cache: true
        name: python3-pip
        state: present
      become: true
      when: os_name == 'rocky'

- name: install packages using loop and package module
  hosts: all
  tags: install_packages
  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - vim
        - python3-pip
        - "{{ apache_package }}"
      become: true

- name: change apache server port
  hosts: all
  tags: apache_port
  become: true
  tasks:
    - name: change port to 8081
      lineinfile:
        path: "{{ apache_conf_path }}"
        regexp: '^Listen 80'
        line: Listen 8081

    - name: restart apache service
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true

    - name: Open the 8081 port
      ansible.posix.firewalld:
        port: 8081/tcp
        permanent: true
        state: enabled
        immediate: yes
      when: os_name == 'rocky'

# provide nginx_state as extra_vars started, stopped, restarted
- name: Deploy nginx index.html
  hosts: ubuntu
  tags: nginx_index_file

  handlers:
    - import_tasks: handlers/main.yaml

  tasks:
    - name: update nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: copy index.html for all servers
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
      vars:
        server_ip: "{{ inventory_hostname  }}"
      become: true
      notify: Restart Nginx

    # - name: "{{ nginx_state }} nginx service"
    #   service:
    #     name: nginx
    #     state: "{{ nginx_state }}"
    #     enabled: true
    #   become: true

- name: docker role usage
  hosts: ubuntu
  become: true
  tags: docker_role
  roles:
    - docker

