---
- name: ping servers
  hosts: all
  tags: 
    - ping
    - pingpong
  tasks:
    - name: pinging servers in inventory
      ping:

    # - name: printing server ip address
    #   debug:
    #     msg: "Hi from debug module {{ inventory_hostname  }}"

- name: install packages
  hosts: all
  tags: install
  tasks:
    - name: install nginx on ubuntu servers
      apt:
        update_cache: true
        name: nginx
        state: present
      become: true
      when: os_name == 'ubuntu'

    - name: install nginx on rocky servers
      dnf:
        update_cache: true
        name: nginx
        state: present
      become: true
      when: os_name == 'rocky'

    - name: install python3 on rocky servers
      dnf:
        update_cache: true
        name: python3-pip
        state: present
      become: true
      when: os_name == 'rocky'

# provide nginx_state as extra_vars started, stopped, restarted

- name: Deploy index.html
  hosts: all
  tags: index_file
  tasks:
    - name: update nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: copy index.html for all servers
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
      vars:
        server_ip: "{{ inventory_hostname  }}"
      become: true

    - name: "{{ nginx_state }} nginx service"
      service:
        name: nginx
        state: "{{ nginx_state }}"
        enabled: true
      become: true
